"""Observed export headers and asset roles; no inferred format variants."""

ADAPTER = "sensor-recorder-arkit-1.5-build5-v1"

POSE_HEADER = [
    "frame_index",
    "record_slot",
    "sensor_sec",
    "utc_sec",
    "tx_m",
    "ty_m",
    "tz_m",
    "qw",
    "qx",
    "qy",
    "qz",
    "exposure_sec",
    "tracking_state",
    "fx_px",
    "fy_px",
    "cx_px",
    "cy_px",
    "width_px",
    "height_px",
]

STREAM_HEADERS = {
    "accelerometer": ["sensor_sec", "utc_sec", "ax_m_s2", "ay_m_s2", "az_m_s2"],
    "gyroscope": ["sensor_sec", "utc_sec", "gx_rad_s", "gy_rad_s", "gz_rad_s"],
    "magnetometer": ["sensor_sec", "utc_sec", "mx_uT", "my_uT", "mz_uT"],
    "device_motion": [
        "sensor_sec",
        "utc_sec",
        "qw",
        "qx",
        "qy",
        "qz",
        "roll",
        "pitch",
        "yaw",
        "gravity_x_m_s2",
        "gravity_y_m_s2",
        "gravity_z_m_s2",
        "user_accel_x_m_s2",
        "user_accel_y_m_s2",
        "user_accel_z_m_s2",
        "rotation_rate_x_rad_s",
        "rotation_rate_y_rad_s",
        "rotation_rate_z_rad_s",
        "magnetic_field_x_uT",
        "magnetic_field_y_uT",
        "magnetic_field_z_uT",
        "magnetic_accuracy",
        "heading_deg",
    ],
    "imu": [
        "sensor_sec",
        "utc_sec",
        "ax_m_s2",
        "ay_m_s2",
        "az_m_s2",
        "gx_rad_s",
        "gy_rad_s",
        "gz_rad_s",
        "accel_sensor_sec",
        "gyro_sensor_sec",
    ],
}

ROLES = {
    "wide.mp4": "rgb",
    "meta.json": "metadata",
    "arkit_pose.csv": "pose_calibration",
    "accelerometer.csv": "accelerometer",
    "gyroscope.csv": "gyroscope",
    "magnetometer.csv": "magnetometer",
    "device_motion.csv": "device_motion",
    "imu.csv": "imu",
}
